// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_pcap
DataFrame read_pcap(std::string capture_file);
RcppExport SEXP crafter_read_pcap(SEXP capture_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type capture_file(capture_fileSEXP);
    __result = Rcpp::wrap(read_pcap(capture_file));
    return __result;
END_RCPP
}
