protocol_numbers <- structure(list(protocol = c("0", "1", "2", "3", "4", "5", "6",
"7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17",
"18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28",
"29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39",
"40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50",
"51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61",
"62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72",
"73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83",
"84", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93",
"94", "95", "96", "97", "98", "99", "100", "101", "102", "103",
"104", "105", "106", "107", "108", "109", "110", "111", "112",
"113", "114", "115", "116", "117", "118", "119", "120", "121",
"122", "123", "124", "125", "126", "127", "128", "129", "130",
"131", "132", "133", "134", "135", "136", "137", "138", "139",
"140", "141", "142", "143-252", "253", "254", "255"), protocol_name = c("HOPOPT",
"ICMP", "IGMP", "GGP", "IPv4", "ST", "TCP", "CBT", "EGP", "IGP",
"BBN-RCC-MON", "NVP-II", "PUP", "ARGUS", "EMCON", "XNET", "CHAOS",
"UDP", "MUX", "DCN-MEAS", "HMP", "PRM", "XNS-IDP", "TRUNK-1",
"TRUNK-2", "LEAF-1", "LEAF-2", "RDP", "IRTP", "ISO-TP4", "NETBLT",
"MFE-NSP", "MERIT-INP", "DCCP", "3PC", "IDPR", "XTP", "DDP",
"IDPR-CMTP", "TP++", "IL", "IPv6", "SDRP", "IPv6-Route", "IPv6-Frag",
"IDRP", "RSVP", "GRE", "DSR", "BNA", "ESP", "AH", "I-NLSP", "SWIPE (deprecated)",
"NARP", "MOBILE", "TLSP", "SKIP", "IPv6-ICMP", "IPv6-NoNxt",
"IPv6-Opts", "", "CFTP", "", "SAT-EXPAK", "KRYPTOLAN", "RVD",
"IPPC", "", "SAT-MON", "VISA", "IPCV", "CPNX", "CPHB", "WSN",
"PVP", "BR-SAT-MON", "SUN-ND", "WB-MON", "WB-EXPAK", "ISO-IP",
"VMTP", "SECURE-VMTP", "VINES", "TTP", "IPTM", "NSFNET-IGP",
"DGP", "TCF", "EIGRP", "OSPFIGP", "Sprite-RPC", "LARP", "MTP",
"AX.25", "IPIP", "MICP (deprecated)", "SCC-SP", "ETHERIP", "ENCAP",
"", "GMTP", "IFMP", "PNNI", "PIM", "ARIS", "SCPS", "QNX", "A/N",
"IPComp", "SNP", "Compaq-Peer", "IPX-in-IP", "VRRP", "PGM", "",
"L2TP", "DDX", "IATP", "STP", "SRP", "UTI", "SMP", "SM (deprecated)",
"PTP", "ISIS over IPv4", "FIRE", "CRTP", "CRUDP", "SSCOPMCE",
"IPLT", "SPS", "PIPE", "SCTP", "FC", "RSVP-E2E-IGNORE", "Mobility Header",
"UDPLite", "MPLS-in-IP", "manet", "HIP", "Shim6", "WESP", "ROHC",
"", "", "", "Reserved"), description = c("IPv6 Hop-by-Hop Option",
"Internet Control Message", "Internet Group Management", "Gateway-to-Gateway",
"IPv4 encapsulation", "Stream", "Transmission Control", "CBT",
"Exterior Gateway Protocol", "any private interior gateway             \n(used by Cisco for their IGRP)",
"BBN RCC Monitoring", "Network Voice Protocol", "PUP", "ARGUS",
"EMCON", "Cross Net Debugger", "Chaos", "User Datagram", "Multiplexing",
"DCN Measurement Subsystems", "Host Monitoring", "Packet Radio Measurement",
"XEROX NS IDP", "Trunk-1", "Trunk-2", "Leaf-1", "Leaf-2", "Reliable Data Protocol",
"Internet Reliable Transaction", "ISO Transport Protocol Class 4",
"Bulk Data Transfer Protocol", "MFE Network Services Protocol",
"MERIT Internodal Protocol", "Datagram Congestion Control Protocol",
"Third Party Connect Protocol", "Inter-Domain Policy Routing Protocol",
"XTP", "Datagram Delivery Protocol", "IDPR Control Message Transport Proto",
"TP++ Transport Protocol", "IL Transport Protocol", "IPv6 encapsulation",
"Source Demand Routing Protocol", "Routing Header for IPv6",
"Fragment Header for IPv6", "Inter-Domain Routing Protocol",
"Reservation Protocol", "Generic Routing Encapsulation", "Dynamic Source Routing Protocol",
"BNA", "Encap Security Payload", "Authentication Header", "Integrated Net Layer Security  TUBA",
"IP with Encryption", "NBMA Address Resolution Protocol", "IP Mobility",
"Transport Layer Security Protocol        \nusing Kryptonet key management",
"SKIP", "ICMP for IPv6", "No Next Header for IPv6", "Destination Options for IPv6",
"any host internal protocol", "CFTP", "any local network", "SATNET and Backroom EXPAK",
"Kryptolan", "MIT Remote Virtual Disk Protocol", "Internet Pluribus Packet Core",
"any distributed file system", "SATNET Monitoring", "VISA Protocol",
"Internet Packet Core Utility", "Computer Protocol Network Executive",
"Computer Protocol Heart Beat", "Wang Span Network", "Packet Video Protocol",
"Backroom SATNET Monitoring", "SUN ND PROTOCOL-Temporary", "WIDEBAND Monitoring",
"WIDEBAND EXPAK", "ISO Internet Protocol", "VMTP", "SECURE-VMTP",
"VINES", "Transaction Transport Protocol", "Internet Protocol Traffic Manager",
"NSFNET-IGP", "Dissimilar Gateway Protocol", "TCF", "EIGRP",
"OSPFIGP", "Sprite RPC Protocol", "Locus Address Resolution Protocol",
"Multicast Transport Protocol", "AX.25 Frames", "IP-within-IP Encapsulation Protocol",
"Mobile Internetworking Control Pro.", "Semaphore Communications Sec. Pro.",
"Ethernet-within-IP Encapsulation", "Encapsulation Header", "any private encryption scheme",
"GMTP", "Ipsilon Flow Management Protocol", "PNNI over IP", "Protocol Independent Multicast",
"ARIS", "SCPS", "QNX", "Active Networks", "IP Payload Compression Protocol",
"Sitara Networks Protocol", "Compaq Peer Protocol", "IPX in IP",
"Virtual Router Redundancy Protocol", "PGM Reliable Transport Protocol",
"any 0-hop protocol", "Layer Two Tunneling Protocol", "D-II Data Exchange (DDX)",
"Interactive Agent Transfer Protocol", "Schedule Transfer Protocol",
"SpectraLink Radio Protocol", "UTI", "Simple Message Protocol",
"Simple Multicast Protocol", "Performance Transparency Protocol",
"", "", "Combat Radio Transport Protocol", "Combat Radio User Datagram",
"", "", "Secure Packet Shield", "Private IP Encapsulation within IP",
"Stream Control Transmission Protocol", "Fibre Channel", "",
"", "", "", "MANET Protocols", "Host Identity Protocol", "Shim6 Protocol",
"Wrapped Encapsulating Security Payload", "Robust Header Compression",
"Unassigned", "Use for experimentation and testing", "Use for experimentation and testing",
""), ipv6_extension_header = c("Y", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "Y", "Y", "", "", "", "", "", "Y", "Y", "", "", "",
"", "", "", "", "", "Y", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "Y", "", "", "", "Y", "Y", "", "", "", "Y", "Y", ""),
    reference = c("[RFC2460]", "[RFC792]", "[RFC1112]", "[RFC823]",
    "[RFC2003]", "[RFC1190][RFC1819]", "[RFC793]", "[Tony_Ballardie]",
    "[RFC888][David_Mills]", "[Internet_Assigned_Numbers_Authority]",
    "[Steve_Chipman]", "[RFC741][Steve_Casner]", "[Boggs, D., J. Shoch, E. Taft, and R. Metcalfe, \"PUP: An\nInternetwork Architecture\", XEROX Palo Alto Research Center,\nCSL-79-10, July 1979; also in IEEE Transactions on\nCommunication, Volume COM-28, Number 4, April 1980.][[XEROX]]",
    "[Robert_W_Scheifler]", "[<mystery contact>]", "[Haverty, J., \"XNET Formats for Internet Protocol Version 4\",\nIEN 158, October 1980.][Jack_Haverty]",
    "[J_Noel_Chiappa]", "[RFC768][Jon_Postel]", "[Cohen, D. and J. Postel, \"Multiplexing Protocol\", IEN 90,\nUSC/Information Sciences Institute, May 1979.][Jon_Postel]",
    "[David_Mills]", "[RFC869][Bob_Hinden]", "[Zaw_Sing_Su]",
    "[\"The Ethernet, A Local Area Network: Data Link Layer and\nPhysical Layer Specification\", AA-K759B-TK, Digital\nEquipment Corporation, Maynard, MA.  Also as: \"The\nEthernet - A Local Area Network\", Version 1.0, Digital\nEquipment Corporation, Intel Corporation, Xerox\nCorporation, September 1980.  And: \"The Ethernet, A Local\nArea Network: Data Link Layer and Physical Layer\nSpecifications\", Digital, Intel and Xerox, November 1982.\nAnd: XEROX, \"The Ethernet, A Local Area Network: Data Link\nLayer and Physical Layer Specification\", X3T51/80-50,\nXerox Corporation, Stamford, CT., October 1980.][[XEROX]]",
    "[Barry_Boehm]", "[Barry_Boehm]", "[Barry_Boehm]", "[Barry_Boehm]",
    "[RFC908][Bob_Hinden]", "[RFC938][Trudy_Miller]", "[RFC905][<mystery contact>]",
    "[RFC969][David_Clark]", "[Shuttleworth, B., \"A Documentary of MFENet, a National\nComputer Network\", UCRL-52317, Lawrence Livermore Labs,\nLivermore, California, June 1977.][Barry_Howard]",
    "[Hans_Werner_Braun]", "[RFC4340]", "[Stuart_A_Friedberg]",
    "[Martha_Steenstrup]", "[Greg_Chesson]", "[Wesley_Craig]",
    "[Martha_Steenstrup]", "[Dirk_Fromhein]", "[Dave_Presotto]",
    "[RFC2473]", "[Deborah_Estrin]", "[Steve_Deering]", "[Steve_Deering]",
    "[Sue_Hares]", "[RFC2205][RFC3209][Bob_Braden]", "[RFC2784][Tony_Li]",
    "[RFC4728]", "[Gary Salamon]", "[RFC4303]", "[RFC4302]",
    "[K_Robert_Glenn]", "[John_Ioannidis]", "[RFC1735]", "[Charlie_Perkins]",
    "[Christer_Oberg]", "[Tom_Markson]", "[RFC2460]", "[RFC2460]",
    "[RFC2460]", "[Internet_Assigned_Numbers_Authority]", "[Forsdick, H., \"CFTP\", Network Message, Bolt Beranek and\nNewman, January 1982.][Harry_Forsdick]",
    "[Internet_Assigned_Numbers_Authority]", "[Steven_Blumenthal]",
    "[Paul Liu]", "[Michael_Greenwald]", "[Steven_Blumenthal]",
    "[Internet_Assigned_Numbers_Authority]", "[Steven_Blumenthal]",
    "[Gene_Tsudik]", "[Steven_Blumenthal]", "[David Mittnacht]",
    "[David Mittnacht]", "[Victor Dafoulas]", "[Steve_Casner]",
    "[Steven_Blumenthal]", "[William_Melohn]", "[Steven_Blumenthal]",
    "[Steven_Blumenthal]", "[Marshall_T_Rose]", "[Dave_Cheriton]",
    "[Dave_Cheriton]", "[Brian Horn]", "[Jim_Stevens]", "[Jim_Stevens]",
    "[Hans_Werner_Braun]", "[M/A-COM Government Systems, \"Dissimilar Gateway Protocol\nSpecification, Draft Version\", Contract no. CS901145,\nNovember 16, 1987.][Mike_Little]",
    "[Guillermo_A_Loyola]", "[Cisco Systems, \"Gateway Server Reference Manual\", Manual\nRevision B, January 10, 1988.][Guenther_Schreiner]",
    "[RFC1583][RFC2328][RFC5340][John_Moy]", "[Welch, B., \"The Sprite Remote Procedure Call System\",\nTechnical Report, UCB/Computer Science Dept., 86/302,\nUniversity of California at Berkeley, June 1986.][Bruce Willins]",
    "[Brian Horn]", "[Susie_Armstrong]", "[Brian_Kantor]", "[John_Ioannidis]",
    "[John_Ioannidis]", "[Howard_Hart]", "[RFC3378]", "[RFC1241][Robert_Woodburn]",
    "[Internet_Assigned_Numbers_Authority]", "[[RXB5]]", "[Bob_Hinden][November 1995, 1997.]",
    "[Ross_Callon]", "[RFC4601][Dino_Farinacci]", "[Nancy_Feldman]",
    "[Robert_Durst]", "[Michael_Hunter]", "[Bob_Braden]", "[RFC2393]",
    "[Manickam_R_Sridhar]", "[Victor_Volpe]", "[CJ_Lee]", "[RFC5798]",
    "[Tony_Speakman]", "[Internet_Assigned_Numbers_Authority]",
    "[RFC3931][Bernard_Aboba]", "[John_Worley]", "[John_Murphy]",
    "[Jean_Michel_Pittet]", "[Mark_Hamilton]", "[Peter_Lothberg]",
    "[Leif_Ekblad]", "[Jon_Crowcroft][draft-perlman-simple-multicast]",
    "[Michael_Welzl]", "[Tony_Przygienda]", "[Criag_Partridge]",
    "[Robert_Sautter]", "[Robert_Sautter]", "[Kurt_Waber]", "[[Hollbach]]",
    "[Bill_McIntosh]", "[Bernhard_Petri]", "[Randall_R_Stewart]",
    "[Murali_Rajagopal][RFC6172]", "[RFC3175]", "[RFC6275]",
    "[RFC3828]", "[RFC4023]", "[RFC5498]", "[RFC7401]", "[RFC5533]",
    "[RFC5840]", "[RFC5858]", "[Internet_Assigned_Numbers_Authority]",
    "[RFC3692]", "[RFC3692]", "[Internet_Assigned_Numbers_Authority]"
    )), .Names = c("protocol", "protocol_name", "description", "ipv6_extension_header",
"reference"), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -148L))
