# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_pcap <- function(capture_file, filter) {
    .Call('crafter_load_pcap', PACKAGE = 'crafter', capture_file, filter)
}

num_packets <- function(pcap) {
    .Call('crafter_num_packets', PACKAGE = 'crafter', pcap)
}

crafter_get_ips <- function(pcap, src_or_dst = "src") {
    .Call('crafter_crafter_get_ips', PACKAGE = 'crafter', pcap, src_or_dst)
}

get_icmp_layer <- function(pcap) {
    .Call('crafter_get_icmp_layer', PACKAGE = 'crafter', pcap)
}

get_packet_info <- function(pcap) {
    .Call('crafter_get_packet_info', PACKAGE = 'crafter', pcap)
}

get_ip_layer <- function(pcap) {
    .Call('crafter_get_ip_layer', PACKAGE = 'crafter', pcap)
}

get_payload_for <- function(pcap, packet_num) {
    .Call('crafter_get_payload_for', PACKAGE = 'crafter', pcap, packet_num)
}

get_tcp_layer <- function(pcap) {
    .Call('crafter_get_tcp_layer', PACKAGE = 'crafter', pcap)
}

