# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
read_pcap <- function(capture_file) {
    .Call('crafter_read_pcap', PACKAGE = 'crafter', capture_file)
}

